[package]
name = "rpwgen"
version = "0.1.0"
authors = ["taronaldinho <kotaro.yamashita@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
rand = "0.7"
rand_distr = "0.2"